stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
      - data/raw_data/raw.csv
      - src/data/split_data.py
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - src/data/normalize_data.py
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - src/models/train_model.py
    outs:
      - models/final_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - models/final_model.pkl
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - src/models/evaluate_model.py
    outs:
      - data/processed_data/predictions.csv
      - metrics/scores.json
